version: "3.7"
volumes: {}
services:

  techdocs:
    image: skhatri/techdocs
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      techmesh:
        aliases:
          - techdocs
    environment:
      - SERVICE_NAME=1
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=ap-southeast-1
      - AWS_ENDPOINT_URL=http://minio:9000
      - AWS_S3_BUCKET_NAME=techdocs3
      - ENTITY_PATH=platform/data/app
    command:
      - "/opt/app/techdocs/publish.sh"
    volumes:
      - ./techdocs:/opt/app/techdocs
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      minio:
        condition: service_healthy
      minio_init:
        condition: service_started

  minio_init:
    image: skhatri/aws-cli
    build:
      context: .
      dockerfile: Dockerfile-aws
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin 
      - AWS_REGION=ap-southeast-1
    command:
      - "aws"
      - "s3"
      - "mb"
      - "s3://techdocs3"
      - "--endpoint-url"
      - "http://minio:9000"
    networks:
      techmesh:
        aliases:
          - minio_init
    depends_on:
      minio:
        condition: service_healthy

  minio:
    image: "quay.io/minio/minio"
    command: 
      - "server"
      - "/data"
      - "--console-address"
      - "0.0.0.0:9001"
    networks:
      techmesh:
        aliases:
          - minio
    volumes:
      - ./minio:/data
    environment:
      - "A=1"
    expose:
      - "9000"
      - "9001"
    ports:
      - "9001:9001"
      - "9000:9000"
    healthcheck: 
      test: "curl http://localhost:9001"

networks:
  techmesh: {}

